type Query {
    user: User @access(expression: "@=isAuthenticated()")
    tasks: [Task]
    task(id: ID!): Task
}

type Mutation {
    CreateTask(input: CreateTaskInput!): Task!
    ChangeTaskStatus(input: ChangeTaskStatusInput): Task!
    AssignUser(input: AssignUserInput): Task!
    Login(input: LoginInput!): AuthPayload!
}

type AuthPayload {
    token: String!
    user: User!
}

type User {
  id: ID!
  name: String!
  email:  String!
}

type Task {
    id: ID!
    name: String!
    description: String!
    status: String!
}

input LoginInput {
    email: String!
    password: String!
}

input CreateTaskInput {
    name: String!
    description: String!
    assignedUser: String!
}

input ChangeTaskStatusInput {
    id: ID!
    status: String!
}

input AssignUserInput {
    id: ID!
    assignedUser: ID!
}
